import type { FastifyPluginAsync } from "fastify";
import { authRoutes } from "./api/auth/index.js";
import { billingRoutes } from "./api/billing/index.js";
import { campaignsRoutes } from "./api/campaigns/index.js";
import { connectRoutes } from "./api/connect/index.js";
import { domainsRoutes } from "./api/domains/index.js";
import { donationsRoutes } from "./api/donations/index.js";
import { getHealthRoute } from "./api/health/get-health/get-health.controller.js";
import { getHealthReadyRoute } from "./api/health/get-health-ready/get-health-ready.controller.js";
import { interestsRoutes } from "./api/interests/index.js";
import { ordersRoutes } from "./api/orders/index.js";
import { payoutsRoutes } from "./api/payouts/index.js";
import { productCategoriesRoutes } from "./api/product-categories/index.js";
import { productsRoutes } from "./api/products/index.js";
import { reportsRoutes } from "./api/reports/index.js";
import { storesRoutes } from "./api/stores/index.js";
import { uploadsRoutes } from "./api/uploads/index.js";
import { webhooksRoutes } from "./api/webhooks/index.js";
import { authHook, permissionsHook } from "./hooks/auth.js";

export const httpRoutes: FastifyPluginAsync = async (app) => {
  app.addHook("onRequest", authHook);
  app.addHook("onRequest", permissionsHook);
  await app.register(getHealthRoute);
  await app.register(getHealthReadyRoute);
  await app.register(authRoutes);
  await app.register(uploadsRoutes);
  await app.register(storesRoutes);
  await app.register(connectRoutes);
  await app.register(billingRoutes);
  await app.register(productCategoriesRoutes);
  await app.register(productsRoutes);
  await app.register(campaignsRoutes);
  await app.register(donationsRoutes);
  await app.register(interestsRoutes);
  await app.register(payoutsRoutes);
  await app.register(ordersRoutes);
  await app.register(reportsRoutes);
  await app.register(domainsRoutes);
  await app.register(webhooksRoutes);
};
